
exports.seed = function(knex, Promise) {
 return Promise.join(
   // Deletes ALL existing entries
   knex('beertypes').del(),

   // Inserts seed entries
   knex('beertypes').insert(
       {
           id: 1,
           name: 'American Amber Ale',
           description: 'American-style amber ales have medium-high to high maltiness with medium to low caramel character. They are characterized by American-variety hops, which produce medium hop bitterness, flavor and aroma. American ambers are usually darker in color, have more caramel flavor and less hop aromatics, and may have more body. This style was first made popular by brewers from California and the Pacific Northwest.',
           colornum: '11 - 18 SRM',
           bitterness: '30 - 45 IBU',
           alcoholnum: '4.4% - 6.1% ABV',
           foodpairings: 'Barbecue, Medium Cheddar, Banana Pound Cake',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Copper to Reddish Brown',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Citrus-like character is acceptable' ,
           malt:'Caramel' ,
           esters:'There may be below levels of fuity-ester flavor' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium' ,
           hopsingr:'Horizon, Cascade, Centennial' ,
           maltingr:'English Pale Ale or American Two-Row, Crystal, Victory' ,
           water:'Varies' ,
           yeast:'Ale' 
               }),
   knex('beertypes').insert(
       {
           id: 2,
           name: 'American Amber Lager',
           description: 'A widely available, sessionable craft beer style that showcases both malt and hops. Amber Lagers are a medium bodied lager with a toasty or caramel-like malt character. Hop bitterness can range from very low to medium-high. Brewers may use decoction mash and dry-hopping to achieve advanced flavors.',
           colornum: '6 - 14 SRM',
           bitterness: '18 - 30 IBU',
           alcoholnum: '4.8% - 5.8% ABV',
           foodpairings: 'Grilled Meats and Vegetables, White Cheddar, Fruit Desserts',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Gold to Copper',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop flavor and aroma are very low to medium-high. Hop bitterness is very-low to medium-high' ,
           malt:'Low to medium-low caramel-type or toasted malt aromas are often present' ,
           esters:'Not Common' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium' ,
           hopsingr:'German Noble' ,
           maltingr:'Two-Row, Munich, Vienna, Caramel' ,
           water:'Varies' ,
           yeast:'Lager' 
             }),
   knex('beertypes').insert(
       {
           id: 3,
           name: 'American Barley Wine',
           description: 'These ales range from amber to deep red/copper-garnet in color. A caramel and/or toffee aroma and flavor are often part of the malt character along with high residual malty sweetness. Complexity of alcohols is evident. Fruity-ester character is often high. As with many American versions of a style, this barley wine ale is typically more hop-forward and bitter than its U.K. counterpart. Low levels of age-induced oxidation can harmonize with other flavors and enhance the overall experience. Sometimes sold as vintage releases.',
           colornum: '11 - 22 SRM',
           bitterness: '60 - 100 IBU',
           alcoholnum: '8.4% - 12% ABV',
           foodpairings: 'Beef Cheek, Strong Blue Cheeses, Rich Desserts',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Amber to Deep Red or Copper-Garnet',
           clarity:'Clear to Brilliant' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable to Hot' ,
           hop:'Hop aroma and flavor are medium to very high. Hop bitterness is high. American-type hops are often used, but not necessary for this style' ,
           malt:'Caramel, Toffee, Bready, Sweet' ,
           esters:'Fruit-ester flavors are often high' ,
           phenols:'Not common to style' ,
           body:'Mouth-Coating to Sticky' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Magnum, Chinook, Centennial, Amarillo' ,
           maltingr:'Pale, Crystal, Pale Chocolate, Special "B"' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
     knex('beertypes').insert(
       {
           id: 4,
           name: 'American Black Ale',
           description: 'Characterized by the perception of caramel malt and dark roasted malt flavor and aroma. Hop bitterness is perceived to be medium-high to high. Hop flavor and aroma are medium-high. Fruity, floral and herbal character from hops of all origins may contribute to the overall experience. This beer is often called a black IPA or Cascadian dark ale.',
           colornum: '34 - 38 SRM',
           bitterness: '50 - 70 IBU',
           alcoholnum: '6.0% - 7.5% ABV',
           foodpairings: 'Grilled Shrimp and Grits, Blue Cheeses and Aged Gouda, Chocolate Truffles',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Very Dark to Black',
           clarity:'Clear to Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma is medium-high to high, with hops of all origins contributing fruity, floral, herbal or other notes' ,
           malt:'Medium caramel malt and dark roasted malt aromas are evident' ,
           esters:'Can be Present' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
       knex('beertypes').insert(
       {
           id: 5,
           name: 'American Brett',
           description: 'These unique beers vary in color and can take on the hues of added fruits or other ingredients.The evolution of natural acidity develops balanced complexity. Horsey, goaty, leathery, phenolic and some fruity acidic character derived from Brettanomyces organisms may be evident, but in balance with other components of the beer. Brett beer and sour beer are not synonymous. Brett beer may contain acidic components, but the presence of acidity in all Brettanomyces beers should not be assumed or dominate. Horsey, goaty, leathery, and phenolic characteristics derived from Brettanomyces organisms may be evident, not dominant and in balance with other character.',
           colornum: 'Varies',
           bitterness: 'Varies',
           alcoholnum: 'Varies',
           foodpairings: 'Grilled or Roasted Game, Earthy Farmhouse Cheeses, Fruit-Filled Pastries',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Varies',
           clarity:'Varies' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Hop aroma, flavor and bitterness are evident over a full range from low to high' ,
           malt:'Varies' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Varies' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Brettanomyces, Ale/Lager possible' 
            }),
         knex('beertypes').insert(
       {
           id: 6,
           name: 'American Brown Ale',
           description: 'Roasted malt, caramel-like and chocolate-like characters should be of medium intensity in both flavor and aroma. American-style brown ales have evident low to medium hop flavor and aroma and medium to high hop bitterness. The history of this style dates back to U.S. homebrewers who were inspired by English-style brown ales and porters. It sits in flavor between those British styles and is more bitter than both.',
           colornum: '15 - 26 SRM',
           bitterness: '24 - 45 IBU',
           alcoholnum: '4.0% - 6.4% ABV',
           foodpairings: 'Grilled Meats and Vegetables, Aged Gouda, Pear Fritters',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Deep Copper to Very Dark Brown',
           clarity:'Clear' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor are low to medium. Hop bitternessis medium to high' ,
           malt:'Caramel, Chocolate, Toast' ,
           esters:'Fruity-ester flavors, if present, should be subdued' ,
           phenols:'Not Common' ,
           body:'Varies' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'Medium' ,
           hopsingr:'U.S., U.K., Noble' ,
           maltingr:'Pale, Crystal, Chocolate, Victory' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
           knex('beertypes').insert(
       {
           id: 7,
           name: 'American Cream Ale',
           description: 'This is a mild, pale, light-bodied ale, made using a warm fermentation (top or bottom fermenting yeast) and cold lagering. Despite being called an ale, when being judged in competitions it is acceptable for brewers to use lager yeast.',
           colornum: '2 - 5 SRM',
           bitterness: '10 - 22 IBU',
           alcoholnum: '4.3% - 5.7% ABV',
           foodpairings: 'Salads and Mild Shellfish, Monterey Jack, Lemon Custard Tart',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Gold',
           clarity:'Brilliant' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma is usually absent, and hop flavor is very low to low. Hop bitterness is very low to low' ,
           malt:'Grainy' ,
           esters:'Not Common' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'High' ,
           finishlength:'Short' ,
           attenuation:'High' ,
           hopsingr:'Liberty' ,
           maltingr:'Pilsner' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
             knex('beertypes').insert(
       {
           id: 8,
           name: 'American Imperial Porter',
           description: 'Definitively American, these porters should have no roasted barley flavors or strong burnt/black malt character. Medium caramel and cocoa-like sweetness is present, with complementing hop character and malt-derived sweetness.',
           colornum: '39 - 40 SRM',
           bitterness: '35 - 50 IBU',
           alcoholnum: '7.0% - 12.0% ABV',
           foodpairings: 'Chicken Mole Enchiladas, Smoked Gouda, Blondie Butterscotch Brownies',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Black',
           clarity:'Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable' ,
           hop:'Hop aroma and flavor are low to medium-high. Hop bitterness is medium-low to medium' ,
           malt:'No roasted barley or strong burnt/black malt character should be perceived. Medium malt, caramal and coacoa-like sweetness is present' ,
           esters:'Ale-like fruity ester flavors should be evident but not overpowering, complementing hop character and malt-derived sweetness' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
               knex('beertypes').insert(
       {
           id: 9,
           name: 'American Imperial Red Ale',
           description: 'The use of American hops in this ale lends to the perception of medium hop bitterness, flavor and aroma. Coupled with a solid malt profile, this should be a beer with balance between hop bitterness and malt sweetness. Some breweries will choose to bottle-condition this style, leading to possible fruity esters and some haze in their appearance. This is another example of modern American brewers taking an established style and boosting the flavor. California brewers are credited with creating this innovative style.',
           colornum: '10 - 17 SRM',
           bitterness: '55 - 85 IBU',
           alcoholnum: '8.0% - 10.6% ABV',
           foodpairings: 'Corned Beef Hash, Mozzarella, Toffee Pudding',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Deep Amber to Dark Copper or Reddish Brown',
           clarity:'Slight Haze to Clear. Unfiltered versions: Hazy to Very Cloudy' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma, flavor and bitterness are high but balanced, arising from any variety of hops' ,
           malt:'Medium to high caramel malt character is present' ,
           esters:'Medium' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                 knex('beertypes').insert(
       {
           id: 10,
           name: 'American Imperial Stout',
           description: 'American-style imperial stouts are the strongest in alcohol and body of the stouts. Black in color, these beers typically have an extremely rich malty flavor and aroma with full, sweet malt character. Bitterness can come from roasted malts or hop additions.',
           colornum: '39 - 40 SRM',
           bitterness: '50 - 80 IBU',
           alcoholnum: '7.0% - 12.0%',
           foodpairings: 'Foie Gras, Aged Cheeses, Flour-less Chocolate-Cake',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Black',
           clarity:'Opaque' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable' ,
           hop:'Hop aroma and flavor are medium-high to high, with floral, citrus and/or herbal hop aromas. Hop bitterness is medium-high to very high and balanced with the malt character' ,
           malt:'Bittersweet Chocolate, Cocoa, Coffee' ,
           esters:'Fruity esters are generally high' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Long' ,
           attenuation:'Medium' ,
           hopsingr:'Horizon, Kent Goldings' ,
           maltingr:'Pale, Black Roasted Barley, Special "B", CaraMunich, Chocolate, Pale Chocolate' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                   knex('beertypes').insert(
       {
           id: 11,
           name: 'American India Pale Ale / IPA',
           description: 'Characterized by floral, fruity, citrus-like, piney or resinous American-variety hop character, this style is all about hop flavor, aroma and bitterness. This has been the most-entered category at the Great American Beer Festival for more than a decade, and is the top-selling craft beer style in supermarkets and liquor stores across the U.S.',
           colornum: '6 - 15 SRM',
           bitterness: '50 - 70 IBU',
           alcoholnum: '6.3% - 7.5% ABV',
           foodpairings: 'Spicy Tuna Roll, Blue Cheeses, Persimmon Rice Pudding',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Gold to Copper, Red/Brown',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma is high and hop flavor is strong both with floral qualities and citrus-like, piney, resinous or sulfur-like American-variety hop character. Hop bitterness is medium-high to very high' ,
           malt:'Biscuit, Bready, Caramel' ,
           esters:'Citrus, Tropical Fruit, Pine' ,
           phenols:'Not Common' ,
           body:'Soft to Sticky' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium to High' ,
           hopsingr:'Centennial, Simcoe, Amarillo' ,
           maltingr:'American Two-Row' ,
           water:'High mineral content' ,
           yeast:'Ale' 
            }),
                     knex('beertypes').insert(
       {
           id: 12,
           name: 'American Lager',
           description: 'American lager has little in the way of hop and malt character. A straw to gold, very clean and crisp, highly carbonated lager.',
           colornum: '2 - 6 SRM',
           bitterness: '5 - 15 IBU',
           alcoholnum: '3.2% - 4.0% ABV',
           foodpairings: 'Pho, Smear Ripened Cheeses, Kettle Corn Balls',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Gold',
           clarity:'Brilliant to Clear' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild' ,
           hop:'Low' ,
           malt:'Grainy' ,
           esters:'Low fruity-ester flavors are acceptable' ,
           phenols:'N/A' ,
           body:'Drying' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'N/A' ,
           hopsingr:'Variety of bittering hops may be used' ,
           maltingr:'2-Row and 6-Row Barley' ,
           water:'Varies' ,
           yeast:'Lager' 
            }),
                       knex('beertypes').insert(
       {
           id: 13,
           name: 'American Pale Ale',
           description: 'An American interpretation of a classic English style. Characterized by floral, fruity, citrus-like, piney, resinous, or sulfur-like American-variety hop character, producing medium to medium-high hop bitterness, flavor and aroma. American-style pale ales have medium body and low to medium maltiness that may include low caramel malt character.',
           colornum:'3 - 14 SRM',
           bitterness: '20 - 45 IBU',
           alcoholnum: '4.2% - 6.2% ABV',
           foodpairings: 'Roasted or Grilled Meats, Mild or Medium Cheddar, Apple Pie',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Deep Golden to Copper or Light Brown',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma and flavor are medium to medium-high, exhibiting fruity, floral, and citrus-like American-variety hop aromas. Hop bitterness is medium to medium-high' ,
           malt:'Biscuit, Bready, Caramel' ,
           esters:'Citrus, Tropical Fruit, Pine' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Horizon, Cascade, Centennial' ,
           maltingr:'Pale, Caramel, Munich' ,
           water:'Sulfite content may vary, but carbonate content should be relatively low' ,
           yeast:'Ale' 
            }),
                         knex('beertypes').insert(
       {
           id: 14,
           name: 'American Sour',
           description: 'The acidity present in these beers is usually in the form of lactic, acetic and other organic acids naturally developed with acidified malt in the mash, or produced during fermentation by the use of various microorganisms. These beers may derive their sour flavor from pure cultured forms of souring agents or from the influence of barrel aging.',
           colornum: 'Varies',
           bitterness: 'Varies',
           alcoholnum: 'Varies',
           foodpairings: 'Varies, Strongly Flavored Cheeses, Creamy Desserts with Fruit',
           glassware: 'Goblet',
           servingtemp: '40 - 50 °F',
           colortxt: 'Any range of color, and may take on the color of other ingredients',
           clarity:'Varies' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Hop aroma, flavor and bitterness are evident over a full range from low to high' ,
           malt:'In darker versions, roasted malt, caramel-like and chocolate-like aromas are subtly present' ,
           esters:'Moderate to intense, yet balanced, fruity ester aromas are evident' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Varies' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale, Brettanomyces possible' 
            }),
                           knex('beertypes').insert(
       {
           id: 15,
           name: 'American Stout',
           description: 'A coffee- and chocolate-forward ale, but with a hop aroma and flavor, often from a citrus-forward variety. American stouts are bold, with a distinctive dry-roasted bitterness in the finish. Fruity esters should be low, but head retention high. The addition of oatmeal is acceptable in this style and lends to the body and head retention.',
           colornum: '39 - 40 SRM',
           bitterness: '35 - 60 IBU',
           alcoholnum: '5.7% - 8.9% ABV',
           foodpairings: 'Grilled Lamb, Sharp Cheddar, Coffee Cake',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Black',
           clarity:'Clear to Opaque' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor are medium to high, often with American citrus-type and/or resiny hop aromas. Hop bitterness is medium to high' ,
           malt:'Low to medium malt sweetness with low to medium caramel, chocolate, and/or roasted coffee flavor is present, with a distinctive dry-roasted bitterness in the finish. The contribution of roasted barley and roasted malt to astringency is low and not excessive. Slight roasted malt acidity is acceptable' ,
           esters:'Fruity-esters flavors are low, if present' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium-high' ,
           hopsingr:'Horizon, Centennial' ,
           maltingr:'Pale, Black Roasted Barley, Chocolate, Crystal' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 16,
           name: 'American-Style Wheat Wine Ale',
           description: 'Part of the “strong ale” category, this ale is not derived from grapes as its name might suggest. Made with at least 50 percent wheat malt, this full-bodied beer features bready and candy flavors, and finishes with a great deal of malty sweetness. These beers may be oak-aged and sometimes have small amounts of darker malts added.',
           colornum: '5 - 15 SRM',
           bitterness: '45 - 85 IBU',
           alcoholnum: '8.5% - 12.2% ABV',
           foodpairings: 'Smoked Trout, Asiago, Peach Sorbet',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Gold to Light Brown',
           clarity:'Slight Haze' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable to Harsh' ,
           hop:'Hop aroma and flavor are low to medium. Hop bitterness is medium to medium-high' ,
           malt:'Bready, wheat, honey-like and/or caramel malt aromas are often present' ,
           esters:'Fruity-ester aroma is often high and counterbalanced with complex alcohol character' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Medium' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'At least 50% Malted Wheat' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 17,
           name: 'American Wheat',
           description: 'Color is pale to light amber. This beer can be made using either ale or lager yeast. Generally brewed with at least 30 percent malted wheat. These beers are typically served with the yeast in the bottle, and pour cloudy. Traditionally more hoppy than a German hefeweizen, American wheat beer differs in that it should not offer flavors of banana or clove. it is a refreshing summer style. Darker versions of this style also exist but are not as common.',
           colornum: '2 - 10 SRM',
           bitterness: '10 - 35 IBU',
           alcoholnum: '3.5% - 5.6% ABV',
           foodpairings: 'Salads and Seafood, Chevre, Fruit Desserts',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Light Amber',
           clarity:'Brilliant to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma, flavor and bitterness are low to medium' ,
           malt:'Grainy Wheat' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Varies' ,
           attenuation:'Medium-high' ,
           hopsingr:'Willamette, Centennial' ,
           maltingr:'Malted Wheat, American Two-Row' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 18,
           name: 'Baltic-Style Porter',
           description: 'A smooth, cold-fermented and cold-lagered beer brewed with lager yeast. Because of its alcoholic strength, it may include very low to low complex alcohol flavors and/or lager fruitiness such as berries, grapes and plums (but not banana; ale-like fruitiness from warm-temperature fermentation is not appropriate). This style has the malt flavors of a brown porter and the roast of a schwarzbier, but is bigger in alcohol and body.',
           colornum: '39 - 40 SRM',
           bitterness: '35 - 40 IBU',
           alcoholnum: '7.6% - 9.3% ABV',
           foodpairings: 'Prime Rib, Aged Gouda, Deconstructed Smores,',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Very Deep Ruby or Garnet to Black',
           clarity:'Clear to Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable' ,
           hop:'Hop aroma and flavor are very low. Hop bitterness is low to medium-low' ,
           malt:'Distinctive malt aromas of caramelized sugars, licorice, and chocolate-like notes of roasted malts and dark sugars are present. Roasted dark malts sometimes contribute a coffee-like roasted barley aroma. Low smoky aroma from malt may be evident. Debittered roasted malts are best used for this style' ,
           esters:'May include very low to low complex alcohol flavors and/or lager fruitiness such as berries, grapes, plums, but not banana; ale-like fruitiness from warm temperature fermentation is not appropriate' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Munich, Vienna, Pilsner, Crystal, Special "B", Carafa Special II, Chocolate' ,
           water:'Varies' ,
           yeast:'Lager' 
            }),
                             knex('beertypes').insert(
       {
           id: 19,
           name: 'Barrel-Aged Beer',
           description: 'A wood- or barrel-aged beer is any lager, ale or hybrid beer, either a traditional style or a unique experimental beer, that has been aged for a period of time in a wooden barrel or in contact with wood. This beer is aged with the intention of imparting the unique character of the wood and/or the flavor of what has previously been in the barrel. Today’s craft brewers are using wood (mostly oak) to influence flavor, and aromatics. Beer may be aged in wooden barrels (new or previously used to age wine or spirits), or chips, spirals and cubes may be added to the conditioning tanks that normally house beer. A variety of types of wood are used including oak, apple, alder, hickory and more. The interior of most barrels is charred or toasted to further enhance the flavor of the wood.',
           colornum: 'Varies',
           bitterness: 'Varies',
           alcoholnum: 'Varies',
           foodpairings: 'Varies',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Varies',
           clarity:'Varies' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Varies' ,
           malt:'Varies' ,
           esters:'Varies' ,
           phenols:'Varies' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Varies' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Lager or Ale. May have Brettanomyces character' 
            }),
                             knex('beertypes').insert(
       {
           id: 20,
           name: 'Belgian-Style Blonde Ale',
           description: 'Typically easy-drinking, with a low but pleasing hop bitterness. This is a light- to medium-bodied ale, with a low malt aroma that has a spiced and sometimes fruity-ester character. Sugar is sometimes added to lighten the perceived body. This style is medium in sweetness and not as bitter as Belgian-style tripels or golden strong ales. It is usually brilliantly clear. The overall impression is balance between light sweetness, spice and low to medium fruity ester flavors.',
           colornum: '4 - 7 SRM',
           bitterness: '15 - 30 IBU',
           alcoholnum: '6.3% - 7.9% ABV',
           foodpairings: 'Sweet and Sour Chicken, Brie, Angel Food Cake',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Pale to Light Amber',
           clarity:'Clear to Brilliant' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop flavor and aroma are not perceived to low. Hop bitterness is very low to low' ,
           malt:'Malt aroma and flavor are low' ,
           esters:'Low to medium fruity-ester aromas may be present and balanced with light malt and spice aromas' ,
           phenols:'Spicy' ,
           body:'Soft to Moderate' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short' ,
           attenuation:'Medium-high' ,
           hopsingr:'Hallertau' ,
           maltingr:'Pilsner, Malted Wheat, Aromatic' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 21,
           name: 'Belgian-Style Dubbel',
           description: 'Belgian-style dubbels range from brown to very dark in color. They have a malty sweetness and can have chocolate-like caramel aroma and flavor. Hop bitterness is medium-low to medium. Yeast-generated fruity esters (especially banana) can be apparent. Often bottle-conditioned, a slight yeast haze and flavor may be evident. ‘Dubbel’ meaning “double,” this beer is still not so big in intensity as to surpass the Belgian-style quadrupel that is often considered its sibling.',
           colornum: '16 - 36 SRM',
           bitterness: '20 - 30 IBU',
           alcoholnum: '6.25% - 7.5% ABV',
           foodpairings: 'Apple-Smoked Sausage, Washed-Rind Cheeses, Milk Chocolate',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Brown to Very Dark',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor medium-low. Hop bitterness is medium-low to medium' ,
           malt:'Chocolate, Caramel, Toast' ,
           esters:'Fruit (Banana)' ,
           phenols:'Spicy, Pepper, Rose-like, Perfumy' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Tettnang' ,
           maltingr:'Pilsner, CaraMunich, Special "B"' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 22,
           name: 'Belgian-Style Flanders',
           description: 'An ale with character and balance, thanks to lactic sourness and acetic acid. Cherry-like flavors are acceptable, as is malt sweetness that can lend bitterness and a cocoa-like character. Oak or other wood-like flavors may be present, even if the beer was not aged in barrels. Overall, the style is characterized by slight to strong lactic sourness, and Flanders “reds” sometimes include a balanced degree of acetic acid. Brettanomyces-produced flavors may be absent or very low. This style is a marvel in flavor complexity, combining malt, yeast, microorganisms, acidity and low astringency from barrel aging.',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 3,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 3,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 3,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 3,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 3,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            })

   );
};