
exports.seed = function(knex, Promise) {
 return Promise.join(
   // Deletes ALL existing entries
   knex('beertypes').del(),

   // Inserts seed entries
   knex('beertypes').insert(
       {
           id: 1,
           name: 'American Amber Ale',
           description: 'American-style amber ales have medium-high to high maltiness with medium to low caramel character. They are characterized by American-variety hops, which produce medium hop bitterness, flavor and aroma. American ambers are usually darker in color, have more caramel flavor and less hop aromatics, and may have more body. This style was first made popular by brewers from California and the Pacific Northwest.',
           colornum: '11 - 18 SRM',
           bitterness: '30 - 45 IBU',
           alcoholnum: '4.4% - 6.1% ABV',
           foodpairings: 'Barbecue, Medium Cheddar, Banana Pound Cake',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Copper to Reddish Brown',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Citrus-like character is acceptable' ,
           malt:'Caramel' ,
           esters:'There may be below levels of fuity-ester flavor' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium' ,
           hopsingr:'Horizon, Cascade, Centennial' ,
           maltingr:'English Pale Ale or American Two-Row, Crystal, Victory' ,
           water:'Varies' ,
           yeast:'Ale' 
               }),
   knex('beertypes').insert(
       {
           id: 2,
           name: 'American Amber Lager',
           description: 'A widely available, sessionable craft beer style that showcases both malt and hops. Amber Lagers are a medium bodied lager with a toasty or caramel-like malt character. Hop bitterness can range from very low to medium-high. Brewers may use decoction mash and dry-hopping to achieve advanced flavors.',
           colornum: '6 - 14 SRM',
           bitterness: '18 - 30 IBU',
           alcoholnum: '4.8% - 5.8% ABV',
           foodpairings: 'Grilled Meats and Vegetables, White Cheddar, Fruit Desserts',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Gold to Copper',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop flavor and aroma are very low to medium-high. Hop bitterness is very-low to medium-high' ,
           malt:'Low to medium-low caramel-type or toasted malt aromas are often present' ,
           esters:'Not Common' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium' ,
           hopsingr:'German Noble' ,
           maltingr:'Two-Row, Munich, Vienna, Caramel' ,
           water:'Varies' ,
           yeast:'Lager' 
             }),
   knex('beertypes').insert(
       {
           id: 3,
           name: 'American Barley Wine',
           description: 'These ales range from amber to deep red/copper-garnet in color. A caramel and/or toffee aroma and flavor are often part of the malt character along with high residual malty sweetness. Complexity of alcohols is evident. Fruity-ester character is often high. As with many American versions of a style, this barley wine ale is typically more hop-forward and bitter than its U.K. counterpart. Low levels of age-induced oxidation can harmonize with other flavors and enhance the overall experience. Sometimes sold as vintage releases.',
           colornum: '11 - 22 SRM',
           bitterness: '60 - 100 IBU',
           alcoholnum: '8.4% - 12% ABV',
           foodpairings: 'Beef Cheek, Strong Blue Cheeses, Rich Desserts',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Amber to Deep Red or Copper-Garnet',
           clarity:'Clear to Brilliant' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable to Hot' ,
           hop:'Hop aroma and flavor are medium to very high. Hop bitterness is high. American-type hops are often used, but not necessary for this style' ,
           malt:'Caramel, Toffee, Bready, Sweet' ,
           esters:'Fruit-ester flavors are often high' ,
           phenols:'Not common to style' ,
           body:'Mouth-Coating to Sticky' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Magnum, Chinook, Centennial, Amarillo' ,
           maltingr:'Pale, Crystal, Pale Chocolate, Special "B"' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
     knex('beertypes').insert(
       {
           id: 4,
           name: 'American Black Ale',
           description: 'Characterized by the perception of caramel malt and dark roasted malt flavor and aroma. Hop bitterness is perceived to be medium-high to high. Hop flavor and aroma are medium-high. Fruity, floral and herbal character from hops of all origins may contribute to the overall experience. This beer is often called a black IPA or Cascadian dark ale.',
           colornum: '34 - 38 SRM',
           bitterness: '50 - 70 IBU',
           alcoholnum: '6.0% - 7.5% ABV',
           foodpairings: 'Grilled Shrimp and Grits, Blue Cheeses and Aged Gouda, Chocolate Truffles',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Very Dark to Black',
           clarity:'Clear to Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma is medium-high to high, with hops of all origins contributing fruity, floral, herbal or other notes' ,
           malt:'Medium caramel malt and dark roasted malt aromas are evident' ,
           esters:'Can be Present' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
       knex('beertypes').insert(
       {
           id: 5,
           name: 'American Brett',
           description: 'These unique beers vary in color and can take on the hues of added fruits or other ingredients.The evolution of natural acidity develops balanced complexity. Horsey, goaty, leathery, phenolic and some fruity acidic character derived from Brettanomyces organisms may be evident, but in balance with other components of the beer. Brett beer and sour beer are not synonymous. Brett beer may contain acidic components, but the presence of acidity in all Brettanomyces beers should not be assumed or dominate. Horsey, goaty, leathery, and phenolic characteristics derived from Brettanomyces organisms may be evident, not dominant and in balance with other character.',
           colornum: 'Varies',
           bitterness: 'Varies',
           alcoholnum: 'Varies',
           foodpairings: 'Grilled or Roasted Game, Earthy Farmhouse Cheeses, Fruit-Filled Pastries',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Varies',
           clarity:'Varies' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Hop aroma, flavor and bitterness are evident over a full range from low to high' ,
           malt:'Varies' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Varies' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Brettanomyces, Ale/Lager possible' 
            }),
         knex('beertypes').insert(
       {
           id: 6,
           name: 'American Brown Ale',
           description: 'Roasted malt, caramel-like and chocolate-like characters should be of medium intensity in both flavor and aroma. American-style brown ales have evident low to medium hop flavor and aroma and medium to high hop bitterness. The history of this style dates back to U.S. homebrewers who were inspired by English-style brown ales and porters. It sits in flavor between those British styles and is more bitter than both.',
           colornum: '15 - 26 SRM',
           bitterness: '24 - 45 IBU',
           alcoholnum: '4.0% - 6.4% ABV',
           foodpairings: 'Grilled Meats and Vegetables, Aged Gouda, Pear Fritters',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Deep Copper to Very Dark Brown',
           clarity:'Clear' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor are low to medium. Hop bitternessis medium to high' ,
           malt:'Caramel, Chocolate, Toast' ,
           esters:'Fruity-ester flavors, if present, should be subdued' ,
           phenols:'Not Common' ,
           body:'Varies' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'Medium' ,
           hopsingr:'U.S., U.K., Noble' ,
           maltingr:'Pale, Crystal, Chocolate, Victory' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
           knex('beertypes').insert(
       {
           id: 7,
           name: 'American Cream Ale',
           description: 'This is a mild, pale, light-bodied ale, made using a warm fermentation (top or bottom fermenting yeast) and cold lagering. Despite being called an ale, when being judged in competitions it is acceptable for brewers to use lager yeast.',
           colornum: '2 - 5 SRM',
           bitterness: '10 - 22 IBU',
           alcoholnum: '4.3% - 5.7% ABV',
           foodpairings: 'Salads and Mild Shellfish, Monterey Jack, Lemon Custard Tart',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Gold',
           clarity:'Brilliant' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma is usually absent, and hop flavor is very low to low. Hop bitterness is very low to low' ,
           malt:'Grainy' ,
           esters:'Not Common' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'High' ,
           finishlength:'Short' ,
           attenuation:'High' ,
           hopsingr:'Liberty' ,
           maltingr:'Pilsner' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
             knex('beertypes').insert(
       {
           id: 8,
           name: 'American Imperial Porter',
           description: 'Definitively American, these porters should have no roasted barley flavors or strong burnt/black malt character. Medium caramel and cocoa-like sweetness is present, with complementing hop character and malt-derived sweetness.',
           colornum: '39 - 40 SRM',
           bitterness: '35 - 50 IBU',
           alcoholnum: '7.0% - 12.0% ABV',
           foodpairings: 'Chicken Mole Enchiladas, Smoked Gouda, Blondie Butterscotch Brownies',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Black',
           clarity:'Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable' ,
           hop:'Hop aroma and flavor are low to medium-high. Hop bitterness is medium-low to medium' ,
           malt:'No roasted barley or strong burnt/black malt character should be perceived. Medium malt, caramal and coacoa-like sweetness is present' ,
           esters:'Ale-like fruity ester flavors should be evident but not overpowering, complementing hop character and malt-derived sweetness' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
               knex('beertypes').insert(
       {
           id: 9,
           name: 'American Imperial Red Ale',
           description: 'The use of American hops in this ale lends to the perception of medium hop bitterness, flavor and aroma. Coupled with a solid malt profile, this should be a beer with balance between hop bitterness and malt sweetness. Some breweries will choose to bottle-condition this style, leading to possible fruity esters and some haze in their appearance. This is another example of modern American brewers taking an established style and boosting the flavor. California brewers are credited with creating this innovative style.',
           colornum: '10 - 17 SRM',
           bitterness: '55 - 85 IBU',
           alcoholnum: '8.0% - 10.6% ABV',
           foodpairings: 'Corned Beef Hash, Mozzarella, Toffee Pudding',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Deep Amber to Dark Copper or Reddish Brown',
           clarity:'Slight Haze to Clear. Unfiltered versions: Hazy to Very Cloudy' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma, flavor and bitterness are high but balanced, arising from any variety of hops' ,
           malt:'Medium to high caramel malt character is present' ,
           esters:'Medium' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                 knex('beertypes').insert(
       {
           id: 10,
           name: 'American Imperial Stout',
           description: 'American-style imperial stouts are the strongest in alcohol and body of the stouts. Black in color, these beers typically have an extremely rich malty flavor and aroma with full, sweet malt character. Bitterness can come from roasted malts or hop additions.',
           colornum: '39 - 40 SRM',
           bitterness: '50 - 80 IBU',
           alcoholnum: '7.0% - 12.0%',
           foodpairings: 'Foie Gras, Aged Cheeses, Flour-less Chocolate-Cake',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Black',
           clarity:'Opaque' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable' ,
           hop:'Hop aroma and flavor are medium-high to high, with floral, citrus and/or herbal hop aromas. Hop bitterness is medium-high to very high and balanced with the malt character' ,
           malt:'Bittersweet Chocolate, Cocoa, Coffee' ,
           esters:'Fruity esters are generally high' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Long' ,
           attenuation:'Medium' ,
           hopsingr:'Horizon, Kent Goldings' ,
           maltingr:'Pale, Black Roasted Barley, Special "B", CaraMunich, Chocolate, Pale Chocolate' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                   knex('beertypes').insert(
       {
           id: 11,
           name: 'American India Pale Ale / IPA',
           description: 'Characterized by floral, fruity, citrus-like, piney or resinous American-variety hop character, this style is all about hop flavor, aroma and bitterness. This has been the most-entered category at the Great American Beer Festival for more than a decade, and is the top-selling craft beer style in supermarkets and liquor stores across the U.S.',
           colornum: '6 - 15 SRM',
           bitterness: '50 - 70 IBU',
           alcoholnum: '6.3% - 7.5% ABV',
           foodpairings: 'Spicy Tuna Roll, Blue Cheeses, Persimmon Rice Pudding',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Gold to Copper, Red/Brown',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma is high and hop flavor is strong both with floral qualities and citrus-like, piney, resinous or sulfur-like American-variety hop character. Hop bitterness is medium-high to very high' ,
           malt:'Biscuit, Bready, Caramel' ,
           esters:'Citrus, Tropical Fruit, Pine' ,
           phenols:'Not Common' ,
           body:'Soft to Sticky' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium to High' ,
           hopsingr:'Centennial, Simcoe, Amarillo' ,
           maltingr:'American Two-Row' ,
           water:'High mineral content' ,
           yeast:'Ale' 
            }),
                     knex('beertypes').insert(
       {
           id: 12,
           name: 'American Lager',
           description: 'American lager has little in the way of hop and malt character. A straw to gold, very clean and crisp, highly carbonated lager.',
           colornum: '2 - 6 SRM',
           bitterness: '5 - 15 IBU',
           alcoholnum: '3.2% - 4.0% ABV',
           foodpairings: 'Pho, Smear Ripened Cheeses, Kettle Corn Balls',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Gold',
           clarity:'Brilliant to Clear' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild' ,
           hop:'Low' ,
           malt:'Grainy' ,
           esters:'Low fruity-ester flavors are acceptable' ,
           phenols:'N/A' ,
           body:'Drying' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'N/A' ,
           hopsingr:'Variety of bittering hops may be used' ,
           maltingr:'2-Row and 6-Row Barley' ,
           water:'Varies' ,
           yeast:'Lager' 
            }),
                       knex('beertypes').insert(
       {
           id: 13,
           name: 'American Pale Ale',
           description: 'An American interpretation of a classic English style. Characterized by floral, fruity, citrus-like, piney, resinous, or sulfur-like American-variety hop character, producing medium to medium-high hop bitterness, flavor and aroma. American-style pale ales have medium body and low to medium maltiness that may include low caramel malt character.',
           colornum:'3 - 14 SRM',
           bitterness: '20 - 45 IBU',
           alcoholnum: '4.2% - 6.2% ABV',
           foodpairings: 'Roasted or Grilled Meats, Mild or Medium Cheddar, Apple Pie',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Deep Golden to Copper or Light Brown',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma and flavor are medium to medium-high, exhibiting fruity, floral, and citrus-like American-variety hop aromas. Hop bitterness is medium to medium-high' ,
           malt:'Biscuit, Bready, Caramel' ,
           esters:'Citrus, Tropical Fruit, Pine' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Horizon, Cascade, Centennial' ,
           maltingr:'Pale, Caramel, Munich' ,
           water:'Sulfite content may vary, but carbonate content should be relatively low' ,
           yeast:'Ale' 
            }),
                         knex('beertypes').insert(
       {
           id: 14,
           name: 'American Sour',
           description: 'The acidity present in these beers is usually in the form of lactic, acetic and other organic acids naturally developed with acidified malt in the mash, or produced during fermentation by the use of various microorganisms. These beers may derive their sour flavor from pure cultured forms of souring agents or from the influence of barrel aging.',
           colornum: 'Varies',
           bitterness: 'Varies',
           alcoholnum: 'Varies',
           foodpairings: 'Varies, Strongly Flavored Cheeses, Creamy Desserts with Fruit',
           glassware: 'Goblet',
           servingtemp: '40 - 50 °F',
           colortxt: 'Any range of color, and may take on the color of other ingredients',
           clarity:'Varies' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Hop aroma, flavor and bitterness are evident over a full range from low to high' ,
           malt:'In darker versions, roasted malt, caramel-like and chocolate-like aromas are subtly present' ,
           esters:'Moderate to intense, yet balanced, fruity ester aromas are evident' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Varies' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale, Brettanomyces possible' 
            }),
                           knex('beertypes').insert(
       {
           id: 15,
           name: 'American Stout',
           description: 'A coffee- and chocolate-forward ale, but with a hop aroma and flavor, often from a citrus-forward variety. American stouts are bold, with a distinctive dry-roasted bitterness in the finish. Fruity esters should be low, but head retention high. The addition of oatmeal is acceptable in this style and lends to the body and head retention.',
           colornum: '39 - 40 SRM',
           bitterness: '35 - 60 IBU',
           alcoholnum: '5.7% - 8.9% ABV',
           foodpairings: 'Grilled Lamb, Sharp Cheddar, Coffee Cake',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Black',
           clarity:'Clear to Opaque' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor are medium to high, often with American citrus-type and/or resiny hop aromas. Hop bitterness is medium to high' ,
           malt:'Low to medium malt sweetness with low to medium caramel, chocolate, and/or roasted coffee flavor is present, with a distinctive dry-roasted bitterness in the finish. The contribution of roasted barley and roasted malt to astringency is low and not excessive. Slight roasted malt acidity is acceptable' ,
           esters:'Fruity-esters flavors are low, if present' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium-high' ,
           hopsingr:'Horizon, Centennial' ,
           maltingr:'Pale, Black Roasted Barley, Chocolate, Crystal' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 16,
           name: 'American-Style Wheat Wine Ale',
           description: 'Part of the “strong ale” category, this ale is not derived from grapes as its name might suggest. Made with at least 50 percent wheat malt, this full-bodied beer features bready and candy flavors, and finishes with a great deal of malty sweetness. These beers may be oak-aged and sometimes have small amounts of darker malts added.',
           colornum: '5 - 15 SRM',
           bitterness: '45 - 85 IBU',
           alcoholnum: '8.5% - 12.2% ABV',
           foodpairings: 'Smoked Trout, Asiago, Peach Sorbet',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Gold to Light Brown',
           clarity:'Slight Haze' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable to Harsh' ,
           hop:'Hop aroma and flavor are low to medium. Hop bitterness is medium to medium-high' ,
           malt:'Bready, wheat, honey-like and/or caramel malt aromas are often present' ,
           esters:'Fruity-ester aroma is often high and counterbalanced with complex alcohol character' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Medium' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'At least 50% Malted Wheat' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 17,
           name: 'American Wheat',
           description: 'Color is pale to light amber. This beer can be made using either ale or lager yeast. Generally brewed with at least 30 percent malted wheat. These beers are typically served with the yeast in the bottle, and pour cloudy. Traditionally more hoppy than a German hefeweizen, American wheat beer differs in that it should not offer flavors of banana or clove. it is a refreshing summer style. Darker versions of this style also exist but are not as common.',
           colornum: '2 - 10 SRM',
           bitterness: '10 - 35 IBU',
           alcoholnum: '3.5% - 5.6% ABV',
           foodpairings: 'Salads and Seafood, Chevre, Fruit Desserts',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Light Amber',
           clarity:'Brilliant to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma, flavor and bitterness are low to medium' ,
           malt:'Grainy Wheat' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Varies' ,
           attenuation:'Medium-high' ,
           hopsingr:'Willamette, Centennial' ,
           maltingr:'Malted Wheat, American Two-Row' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 18,
           name: 'Baltic-Style Porter',
           description: 'A smooth, cold-fermented and cold-lagered beer brewed with lager yeast. Because of its alcoholic strength, it may include very low to low complex alcohol flavors and/or lager fruitiness such as berries, grapes and plums (but not banana; ale-like fruitiness from warm-temperature fermentation is not appropriate). This style has the malt flavors of a brown porter and the roast of a schwarzbier, but is bigger in alcohol and body.',
           colornum: '39 - 40 SRM',
           bitterness: '35 - 40 IBU',
           alcoholnum: '7.6% - 9.3% ABV',
           foodpairings: 'Prime Rib, Aged Gouda, Deconstructed Smores,',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Very Deep Ruby or Garnet to Black',
           clarity:'Clear to Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable' ,
           hop:'Hop aroma and flavor are very low. Hop bitterness is low to medium-low' ,
           malt:'Distinctive malt aromas of caramelized sugars, licorice, and chocolate-like notes of roasted malts and dark sugars are present. Roasted dark malts sometimes contribute a coffee-like roasted barley aroma. Low smoky aroma from malt may be evident. Debittered roasted malts are best used for this style' ,
           esters:'May include very low to low complex alcohol flavors and/or lager fruitiness such as berries, grapes, plums, but not banana; ale-like fruitiness from warm temperature fermentation is not appropriate' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Munich, Vienna, Pilsner, Crystal, Special "B", Carafa Special II, Chocolate' ,
           water:'Varies' ,
           yeast:'Lager' 
            }),
                             knex('beertypes').insert(
       {
           id: 19,
           name: 'Barrel-Aged Beer',
           description: 'A wood- or barrel-aged beer is any lager, ale or hybrid beer, either a traditional style or a unique experimental beer, that has been aged for a period of time in a wooden barrel or in contact with wood. This beer is aged with the intention of imparting the unique character of the wood and/or the flavor of what has previously been in the barrel. Today’s craft brewers are using wood (mostly oak) to influence flavor, and aromatics. Beer may be aged in wooden barrels (new or previously used to age wine or spirits), or chips, spirals and cubes may be added to the conditioning tanks that normally house beer. A variety of types of wood are used including oak, apple, alder, hickory and more. The interior of most barrels is charred or toasted to further enhance the flavor of the wood.',
           colornum: 'Varies',
           bitterness: 'Varies',
           alcoholnum: 'Varies',
           foodpairings: 'Varies',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Varies',
           clarity:'Varies' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Varies' ,
           malt:'Varies' ,
           esters:'Varies' ,
           phenols:'Varies' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Varies' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Lager or Ale. May have Brettanomyces character' 
            }),
                             knex('beertypes').insert(
       {
           id: 20,
           name: 'Belgian-Style Blonde Ale',
           description: 'Typically easy-drinking, with a low but pleasing hop bitterness. This is a light- to medium-bodied ale, with a low malt aroma that has a spiced and sometimes fruity-ester character. Sugar is sometimes added to lighten the perceived body. This style is medium in sweetness and not as bitter as Belgian-style tripels or golden strong ales. It is usually brilliantly clear. The overall impression is balance between light sweetness, spice and low to medium fruity ester flavors.',
           colornum: '4 - 7 SRM',
           bitterness: '15 - 30 IBU',
           alcoholnum: '6.3% - 7.9% ABV',
           foodpairings: 'Sweet and Sour Chicken, Brie, Angel Food Cake',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Pale to Light Amber',
           clarity:'Clear to Brilliant' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop flavor and aroma are not perceived to low. Hop bitterness is very low to low' ,
           malt:'Malt aroma and flavor are low' ,
           esters:'Low to medium fruity-ester aromas may be present and balanced with light malt and spice aromas' ,
           phenols:'Spicy' ,
           body:'Soft to Moderate' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short' ,
           attenuation:'Medium-high' ,
           hopsingr:'Hallertau' ,
           maltingr:'Pilsner, Malted Wheat, Aromatic' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 21,
           name: 'Belgian-Style Dubbel',
           description: 'Belgian-style dubbels range from brown to very dark in color. They have a malty sweetness and can have chocolate-like caramel aroma and flavor. Hop bitterness is medium-low to medium. Yeast-generated fruity esters (especially banana) can be apparent. Often bottle-conditioned, a slight yeast haze and flavor may be evident. ‘Dubbel’ meaning “double,” this beer is still not so big in intensity as to surpass the Belgian-style quadrupel that is often considered its sibling.',
           colornum: '16 - 36 SRM',
           bitterness: '20 - 30 IBU',
           alcoholnum: '6.25% - 7.5% ABV',
           foodpairings: 'Apple-Smoked Sausage, Washed-Rind Cheeses, Milk Chocolate',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Brown to Very Dark',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor medium-low. Hop bitterness is medium-low to medium' ,
           malt:'Chocolate, Caramel, Toast' ,
           esters:'Fruit (Banana)' ,
           phenols:'Spicy, Pepper, Rose-like, Perfumy' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Tettnang' ,
           maltingr:'Pilsner, CaraMunich, Special "B"' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 22,
           name: 'Belgian-Style Flanders',
           description: 'An ale with character and balance, thanks to lactic sourness and acetic acid. Cherry-like flavors are acceptable, as is malt sweetness that can lend bitterness and a cocoa-like character. Oak or other wood-like flavors may be present, even if the beer was not aged in barrels. Overall, the style is characterized by slight to strong lactic sourness, and Flanders “reds” sometimes include a balanced degree of acetic acid. Brettanomyces-produced flavors may be absent or very low. This style is a marvel in flavor complexity, combining malt, yeast, microorganisms, acidity and low astringency from barrel aging.',
           colornum: '12 - 25 SRMM',
           bitterness: '5 - 18 IBU',
           alcoholnum: '4.8% - 6.6% ABV',
           foodpairings: 'Beef Carbonnade, Mimolette, Pumpkin Pie',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Copper to Very Dark',
           clarity:'Brilliant to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma and flavor are not perceived. Hop bitterness is perceived to be very low to medium-low' ,
           malt:'Roasted malt aromas including a cocoa-like character are acceptable at low levels. A very low degree of malt sweetness may be present' ,
           esters:'Fruit-ester aromas, which are often cherry-like, are apparent. May also have notes of raisins, plums, figs and prunes' ,
           phenols:'Not Common' ,
           body:'Varies' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium-high' ,
           hopsingr:'Kent Goldings' ,
           maltingr:'Vienna, Munich Special "B", Aromatic' ,
           water:'Varies' ,
           yeast:'Brettanomyces' 
            }),
                             knex('beertypes').insert(
       {
           id: 23,
           name: 'Belgian-Style Fruit Lambic',
           description: 'Often known as cassis, framboise, kriek, or peche, a fruit lambic takes on the color and flavor of the fruit it is brewed with. It can be dry or sweet, clear or cloudy, depending on the ingredients. Notes of Brettanomyces yeast are often present at varied levels. Sourness is an important part of the flavor profile, though sweetness may compromise the intensity. These flavored lambic beers may be very dry or mildly sweet.',
           colornum: 'Varies',
           bitterness: '15 - 21 IBU',
           alcoholnum: '5.7% - 8.9% ABV',
           foodpairings: 'Pineapple Ceviche, Chevre, Chocolate Creme Caramel',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Hued with color reflecting the choice of fruit',
           clarity:'Varies' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Varies' ,
           hop:'Hop aroma, flavor and bitterness are not perceived to very low, and can include cheesy or floral lavender notes' ,
           malt:'Sweet malt characters are not perceived' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'High' ,
           finishlength:'Varies' ,
           attenuation:'Medium-high' ,
           hopsingr:'Aged, stale hops' ,
           maltingr:'Pilsner, Flaked Wheat' ,
           water:'Varies' ,
           yeast:'Ale, Brettanomyces possible' 
            }),
                             knex('beertypes').insert(
       {
           id: 24,
           name: 'Belgian-Style Golden Strong Ale',
           description: 'These beers are fruity, complex and often on the higher end of the ABV spectrum, yet are approachable to many different palates. Look for a characteristic spiciness from Belgian yeast and a highly attenuated dry finish. This style is traditionally drier and lighter in color than a Belgian-style tripel.',
           colornum: '9 - 35 SRM',
           bitterness: '20 - 50 IBU',
           alcoholnum: '7.0% - 11.0%',
           foodpairings: 'Beer Battered Fried Shrimp, Triple Creme, Baklava',
           glassware: 'Tulip',
           servingtemp: '40 - 45 °F',
           colortxt: 'Pale to Copper',
           clarity:'Clear' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild' ,
           hop:'Hop aroma and flavor are medium-low to medium-high. Hop bitterness is medium-low to medium-high' ,
           malt:'These beers can be malty in overall impression, or dry and highly attenuated' ,
           esters:'Fruit (Pear, Orange, Apple)' ,
           phenols:'Spicy, Pepper' ,
           body:'Soft' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Czech Saaz' ,
           maltingr:'Pilsner' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 25,
           name: 'Belgian-Style Lambic / Gueuze',
           description: 'Naturally and spontaneously fermented beers with high to very high levels of esters, plus bacterial and yeast-derived sourness that sometimes includes acetic flavors. Lambics are not blended, while the gueuze style blends old and new lambics which are re-fermented in the bottle. Historically, they are dry and completely attenuated, exhibiting no residual sweetness either from malt, sugar or artificial sweeteners. Sweet versions may be created through the addition of sugars or artificial sweeteners. Many examples of this style are made to resemble the the gueuze lambic beers of the Brussels area, where it originated.',
           colornum: '6 - 13 SRM',
           bitterness: '9 - 23 IBU',
           alcoholnum: '6.2% - 8.1% ABV',
           foodpairings: 'Mussels, Mascarpone with Fruit, Rich Chocolate Cake',
           glassware: 'Tulip',
           servingtemp: '40 - 50 °F',
           colortxt: 'Gold to Medium Amber',
           clarity:'Brilliant (but haze may exist from yeast sediment from bottle fermentation)' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma, flavor and bitterness are not perceived to very low, and can include cheesy or floral lavender notes' ,
           malt:'Sweet malt characters are not perceived' ,
           esters:'High to very high fruity ester aromas are present' ,
           phenols:'N/A' ,
           body:'Drying to Soft' ,
           carbonationtaste:'Very Low to High' ,
           finishlength:'Medium' ,
           attenuation:'High' ,
           hopsingr:'Aged, stale hops' ,
           maltingr:'Pilsner, Flaked Wheat' ,
           water:'Varies' ,
           yeast:'Ale, Brettanomyces possible' 
            }),
                             knex('beertypes').insert(
       {
           id: 26,
           name: 'Belgian-Style Pale Ale',
           description: 'These pale ales are gold to copper in color and can have caramel or toasted malt flavor. The style is characterized by low but noticeable hop bitterness, flavor and aroma. These beers were inspired by British pale ales. They are very sessionable.',
           colornum: '6 - 12 SRM',
           bitterness: '20 - 30 IBU',
           alcoholnum: '4.0% - 6.0% ABV',
           foodpairings: 'Tempura Fried Fish and Chips, Taleggio, Savory Bread Pudding',
           glassware: 'Tulip',
           servingtemp: '40 - 50 °F',
           colortxt: 'Gold to Copper',
           clarity:'Clear' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma and flavor are low but noticeable; noble-type hops are commonly used. Hop bitterness is low but noticeable' ,
           malt:'Caramel, Toast' ,
           esters:'Fruit (Pear, Orange)' ,
           phenols:'Spicy' ,
           body:'Moderate' ,
           carbonationtaste:'Medium' ,
           finishlength:'Short to Medium' ,
           attenuation:'High' ,
           hopsingr:'Kent Goldings' ,
           maltingr:'Pilsner, CaraMunich, Biscuit' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 27,
           name: 'Belgian-Style Quadrupel',
           description: 'These beers are amber to dark brown in color. Caramel, dark sugar and malty sweet flavors dominate, with medium-low to medium-high hop bitterness. Quads have a relatively light body compared to their alcoholic strength. If aged, oxidative qualities should be mild and not distracting. Sometimes referred to as Belgian strong dark.',
           colornum: '8 - 20 SRM',
           bitterness: '25 - 50 IBU',
           alcoholnum: '7.2% - 11.2% ABV',
           foodpairings: 'Roasted Duck, Aged Gouda, Bread Pudding',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Amber to Dark Brown',
           clarity:'Slight Haze' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable to Hot' ,
           hop:'Hop aroma and flavor are not perceived to very low. Hop bitterness is low to medium-low' ,
           malt:'Caramel, dark sugar and malty sweet flavors and aromas can be intense, not cloying, while complementing fruitiness' ,
           esters:'Complex fruity flavors reminiscent of raisins, dates, figs, grapes and/or plums emerge, often accompanied with a hint of wine-like character. Perception of alcohol can be extreme' ,
           phenols:'Clove-like phenolic flavor and aroma should not be evident' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'High' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 28,
           name: 'Belgian-Style Saison',
           description: 'Beers in this category are pale to deep light brown in color. Often bottle-conditioned, with some yeast character and high carbonation. Belgian-style saison may have Brettanomyces or lactic character, and fruity, horsey, goaty and/or leather-like. aromas and flavors. Specialty ingredients, including spices, may contribute a unique and signature character. Commonly called ‘farmhouse ales’ and originating as summertime beers in Belgium, these are not just warm-weather treats. U.S. craft brewers brew them year-round and have taken to adding a variety of additional ingredients.',
           colornum: '4 - 14 SRM',
           bitterness: '20 - 40 IBU',
           alcoholnum: '4.5% - 8.5% ABV',
           foodpairings: 'Seafood, Brie, Lemon Ginger Sorbet',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Pale to Light Brown',
           clarity:'Slight Haze' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma is low to medium. Hop bitterness is medium to medium-high' ,
           malt:'Malt flavor is low but provides foundation for the overall balance' ,
           esters:'Fruit (Orange, Lemon)' ,
           phenols:'Pepper' ,
           body:'Soft' ,
           carbonationtaste:'High' ,
           finishlength:'Short to Medium' ,
           attenuation:'High' ,
           hopsingr:'Noble, Styrian, East Kent Goldings' ,
           maltingr:'Pilsner, Munich, Malted Wheat' ,
           water:'High sulfate content' ,
           yeast:'Ale, Brettanomyces possible' 
            }),
                             knex('beertypes').insert(
       {
           id: 29,
           name: 'Belgian-Style Tripel',
           description: 'Complex, sometimes mild spicy flavor characterizes this style. Yeast-driven complexity is common. Tripels are often on the higher end of the ABV spectrum, yet are approachable to many different palates. These beers are commonly bottle-conditioned and finish dry. Tripels are similar to Belgian-style golden strong ales, but are generally darker and have a more noticeable malt sweetness.',
           colornum: '4 - 7 SRM',
           bitterness: '20 - 45 IBU',
           alcoholnum: '7.0% - 10.0% ABV',
           foodpairings: 'Roasted Turkey, Triple Creme, Caramelized Banana Creme Brulee',
           glassware: 'Tulip',
           servingtemp: '40 - 45 °F',
           colortxt: 'Pale to Light Amber',
           clarity:'Clear' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Mild' ,
           hop:'Hop aroma and flavor are not perceived to low. Hop bitterness is medium to medium-high' ,
           malt:'Low sweetness from very pale malts is present' ,
           esters:'Fruit (Orange, Banana)' ,
           phenols:'Complex, sometimes mild spicy flavor. Clove-like phenolic flavor may be evident at very low levels' ,
           body:'Soft to Mouth-Coating' ,
           carbonationtaste:'High' ,
           finishlength:'Short to Medium' ,
           attenuation:'High' ,
           hopsingr:'Tetnang, Czech Saaz' ,
           maltingr:'Belgian Pilsner' ,
           water:'Soft Water' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 30,
           name: 'Belgian-Style Witbier',
           description: 'Belgian-style wits are brewed using unmalted wheat, sometimes oats and malted barley. Witbiers are spiced with coriander and orange peel. A style that dates back hundreds of years, it fell into relative obscurity until it was revived by Belgian brewer Pierre Celis in the 1960s. This style is currently enjoying a renaissance, especially in the American market. ‘Wit’ means “white.”',
           colornum: '2 - 4 SRM',
           bitterness: '10 - 17 IBU',
           alcoholnum: '4.8% - 5.6% ABV',
           foodpairings: 'Moules and Frites, Mascarpone, Panna Cotta',
           glassware: 'Tulip',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Pale',
           clarity:'Hazy' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop flavor and aroma are not perceived to low. Hop bitterness is low, achieved traditionally by the use of noble-type hops' ,
           malt:'Malt aroma and flavor are very low to low' ,
           esters:'Orange, Citrus' ,
           phenols:'Spicy, Pepper' ,
           body:'Drying' ,
           carbonationtaste:'High' ,
           finishlength:'Medium' ,
           attenuation:'High' ,
           hopsingr:'German Noble' ,
           maltingr:'Pilsner, Flaked Wheat, Unmalted Wheat, and occasionally oats and malted barley' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 31,
           name: 'Berliner-Style Weisse',
           description: 'Low in alcohol and refreshingly tart, and often served with a flavored syrup like Woodruff or raspberry, this German-style wheat ale presents a harmony between yeast and lactic acid. These beers are very pale in color, and may be cloudy as they are often unfiltered. Hops are not a feature of this style, but these beers often do showcase esters. Traditional versions often showcase Brettanomyces yeast. Growing in popularity in the U.S., where many brewers are now adding traditional and exotic fruits to the recipe, resulting in flavorful finishes with striking, colorful hues. These beers are incredible when pairing. Bitterness, alcohol and residual sugar are very low, allowing the beer’s acidity, white bread and graham cracker malt flavors to shine. Carbonation is very high, adding to the refreshment factor this style delivers. Many examples of this style contain no hops and thus no bitterness at all.',
           colornum: '2 - 4 SRM',
           bitterness: '3 - 6 IBU',
           alcoholnum: '2.8% - 3.4% ABV',
           foodpairings: 'Aged Ham on Pretzel Bread, Havarti, Cheesecake with Raspberries',
           glassware: 'Goblet',
           servingtemp: '45 - 50 °F',
           colortxt: 'Staw to Pale',
           clarity:'Clear to Hazy' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma and flavor are not perceived. Hop bitterness is not perceived to very low' ,
           malt:'Not Perceived' ,
           esters:'Fruity-ester flavors will be evident' ,
           phenols:'Not Common' ,
           body:'Drying' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Short to Medium' ,
           attenuation:'High' ,
           hopsingr:'German Noble' ,
           maltingr:'Pilsner, Malted Wheat' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 32,
           name: 'French-Style Biere De Garde',
           description: 'The name translates as “beer for keeping.” This style is popping up more and more from U.S. producers. Blond, amber and brown versions exist. Bier de garde examples are light amber to chestnut brown or red in color. This style is characterized by a toasted malt aroma and slight malt sweetness. Flavor of alcohol is evident. Often bottle-conditioned, with some yeast character.',
           colornum: '7 - 16 SRM',
           bitterness: '20 - 30 IBU',
           alcoholnum: '4.4% - 8.0% ABV',
           foodpairings: 'Roasted Lamb with Mint, Soft Ripened Cheeses, Pecan Pie',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Light Amber to Chestnut Brown or Red',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor are low to medium, from noble-type hops. Hop bitterness is low to medium' ,
           malt:'Toast, Caramel, Toffee' ,
           esters:'Fruity-ester flavors can be low to medium in intensity' ,
           phenols:'Not Common' ,
           body:'Soft to Mouth-Coating' ,
           carbonationtaste:'High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Fuggle' ,
           maltingr:'CaraVienna, Pilsner, Munich, Black Patent' ,
           water:'Soft Water' ,
           yeast:'Ale, Brettanomyces possible' 
            }),
                             knex('beertypes').insert(
       {
           id: 33,
           name: 'English-Style Bitter',
           description: 'A very sessionable, lower-alcohol, malt-driven style. Broad style description commonly associated with cask-conditioned beers. The light- to medium-bodied ordinary bitter is gold to copper in color, with a low residual malt sweetness. Hop bitterness is medium.',
           colornum: '5 - 12 SRM',
           bitterness: '20 - 35 IBU',
           alcoholnum: '3.0% - 4.2% ABV',
           foodpairings: 'Roasted Chicken and Fish & Chips, Firm English Cheeses, Oatmeal Raisin Walnut Cookies',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Gold to Copper',
           clarity:'Clear to Brilliant' ,
           carbonationvisual:'Slow Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma may be evident at the brewers discretion' ,
           malt:'Low to medium residual malt sweetness is present' ,
           esters:'Fruity esters are common.' ,
           phenols:'Not Common' ,
           body:'Drying to Soft' ,
           carbonationtaste:'Low' ,
           finishlength:'Short ' ,
           attenuation:'Medium-high' ,
           hopsingr:'Kent Goldings' ,
           maltingr:'British Pale Ale, Aromatic, Crystal, Special Roast' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 34,
           name: 'Blonde Ale',
           description: 'One of the most approachable styles, a golden or blonde ale is an easy-drinking beer that is visually appealing and has no particularly dominating malt or hop characteristics. Rounded and smooth, it is an American classic known for its simplicity. Sometimes referred to as ‘golden ale.’ These beers can have honey, spices and fruit added, and may be fermented with lager or ale yeast.',
           colornum: '3 - 7 SRM',
           bitterness: '15 - 25 IBU',
           alcoholnum: '4.1% - 5.1% ABV',
           foodpairings: 'Spaghetti and Meatballs, Pepper Jack, Sugar Cookies',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Straw to Light Amber',
           clarity:'Brilliant to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma is low to medium-low, present but not dominant. Hop bitterness is low to medium-low.' ,
           malt:'Light malt sweetness is present in the flavor. Bread, toast, biscuit and wheat flavors are common.' ,
           esters:'Fruity esters may be perceived but not predominant.' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short' ,
           attenuation:'Medium-high' ,
           hopsingr:'Willamette' ,
           maltingr:'American Two-Row, Crystal' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),

                             //bohemian-style pilsener is supposed to be spelled with an extra "e" don't change it
                             knex('beertypes').insert(
       {
           id: 35,
           name: 'Bohemian-Style Pilsener',
           description: 'Bohemian-style pilseners have a slightly sweet and evident malt character and a toasted, biscuit-like, bready malt character. Hop bitterness is perceived as medium with a low to medium-low level of noble-type hop aroma and flavor. This style originated in 1842, with ‘pilsener’ originally indicating an appellation in the Czech Republic. Classic examples of this style used to be conditioned in wooden tanks and had a less sharp hop bitterness despite the similar IBU ranges to German-style pilsener. Low-level diacetyl is acceptable. Bohemian-style pilseners are darker in color and bigger in final gravity that their German counterparts.',
           colornum: '3 - 7 SRM',
           bitterness: '30 - 45 IBU',
           alcoholnum: '4.1% - 5.1% ABV',
           foodpairings: 'Shellfish and Chicken and Salads, Mild White Cheddar, Shortbread Cookies',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Light Amber',
           clarity:'Clear to Brilliant' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma and flavor are low to medium-low, deriving from noble-type hops. Hop bitterness is medium' ,
           malt:'Toasted, biscuit-like, and/or bready malt flavors along with low levels of fermented-malt-derived sulfur compounds may be evident' ,
           esters:'Not Common' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium' ,
           finishlength:'Short' ,
           attenuation:'Medium' ,
           hopsingr:'Czech Saaz' ,
           maltingr:'Pilsner, CaraPils' ,
           water:'Low Mineral Content' ,
           yeast:'Lager' 
            }),
                             knex('beertypes').insert(
       {
           id: 36,
           name: 'British-Style Barley Wine Ale',
           description: 'A strong ale that leans heavily on malt characteristics for flavor. With a wide color range and typically high in alcohol, this is a style that is often aged and will evolve well over time. As they advance in age, these beers develop oxidative characteristics including honey and toffee flavors and aromas, darker colors, lessened bitterness and more.',
           colornum: '14 - 22 SRM',
           bitterness: '40 - 60 IBU',
           alcoholnum: '8.5% - 12% ABV',
           foodpairings: 'Moroccan Duck, English Stilton, Dark Chocolate',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Tawny Copper to Deep Red or Copper-Garnet',
           clarity:'Brilliant to Slight Haze' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable to Hot' ,
           hop:'Hop flavor and aroma are very low to medium. Hop bitterness is low to medium. English-type hops are often used, but not necessary for this style' ,
           malt:'Nutty, Caramel, Biscuit' ,
           esters:'Fruity-ester characters are often high and balanced with the high alcohol content' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Varies' ,
           attenuation:'Medium' ,
           hopsingr:'Kent Goldings, Horizon' ,
           maltingr:'English Pale, CaraMunich, Crystal' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 37,
           name: 'California Common',
           description: 'This beer style is brewed with lager yeasts but fermented at ale fermentation temperatures. There is a noticeable degree of toasted malt and/or caramel-like malt character in flavor and often in aroma. Often referred to as ‘steam beer’ and made famous by San Francisco’s Anchor Brewing Company. Seek out woody and mint flavor from the Northern Brewer hops.',
           colornum: '8 - 15 SRM',
           bitterness: '35 - 45 IBU',
           alcoholnum: '4.6% - 5.7% ABV',
           foodpairings: 'Pork Loin, Feta, Bread Pudding',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Light Amber to Medium Amber',
           clarity:'Clear' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop flavor is low to medium-low and may present as Woody, Rustic, or Minty. Hop bitterness is medium to medium-high' ,
           malt:'Noticeable caramel-type malt flavor should be present' ,
           esters:'Fruity-ester aromas, if present, should be low to medium-low' ,
           phenols:'Not Common' ,
           body:'Drying' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short' ,
           attenuation:'Medium' ,
           hopsingr:'Northern Brewer' ,
           maltingr:'Pale, Munich, Crystal, Victory, Pale Chocolate' ,
           water:'Varies' ,
           yeast:'Lager' 
            }),
                             knex('beertypes').insert(
       {
           id: 38,
           name: 'Chocolate Beer',
           description: 'This is an ale or lager that benefits from the addition of dark chocolate or cocoa. More common in porters, stouts and brown ales, where the grain bill better complements the confectionery ingredient, it can be added to other styles as well. Overt bitterness is not acceptable in this style. Little hop character is desired and the chocolate flavor does not need to be overwhelming. The style can vary greatly in approach and flavor profile depending on the brewer.',
           colornum: '12 - 50 SRM',
           bitterness: '15 - 40 IBU',
           alcoholnum: '2.5% - 12.0% ABV',
           foodpairings: 'Venison Mole, Aged Goat Cheeses, Raspberry Torte',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Light Brown to Black',
           clarity:'Brilliant to Opaque' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Hop flavor and aroma are lower than might be expected for the style. Under-hopping allows chocolate to contribute to the flavor profile while not becoming excessively bitter. Hop bitterness is very low to medium-low.' ,
           malt:'Medium-low to medium-high malt sweetness helps accent cocoa flavors and aromas.' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Medium-high' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 39,
           name: 'Coffee Beer',
           description: 'As the name suggests, this can be either a lager or ale with coffee added to boost flavor. While stouts and porters are popular base styles for coffee beer, many craft breweries are experimenting with other styles, like cream ales and India pale ales. Brewers may steep the beans in either water or beer to impart java flavor without adding acidity. While stouts and porters are popular base styles for coffee beer, many craft breweries are experimenting with other styles, like cream ales and India pale ales. Barrel-aged or wood-influenced versions may show signs of oxidation, including sherry notes and other advanced flavors.',
           colornum: '4 - 50 SRM',
           bitterness: '15 - 45 IBU',
           alcoholnum: '2.5% - 12.0% ABV',
           foodpairings: 'Pork Tenderloin, Aged Semi-Hard Cheeses, Vanilla Ice Cream',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Pale to Black',
           clarity:'Brilliant to Opaque' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Hop flavor is reflective of aroma and can be low to high depending on the intent of the underlying style. Hop bitterness is very low to medium-high.' ,
           malt:'Medium-low to medium malt sweetness helps accent coffee flavors and aromas.' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Medium-high' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 40,
           name: 'Contemporary Gose',
           description: 'Straw to medium amber, gose is cloudy from suspended yeast. A wide variety of herbal, spice, floral or fruity aromas other than found in traditional Leipzig-Style Gose are present, in harmony with other aromas. Salt (table salt) character is traditional in low amounts, but may vary from absent to present. Body is low to medium-low. Low to medium lactic acid character is evident in all examples as sharp, refreshing sourness.',
           colornum: '3 - 9 SRM',
           bitterness: '10 - 15 IBU',
           alcoholnum: '4.4% - 5.4% ABV',
           foodpairings: 'Watermelon Salad, Queso Fresco, Greek Yogurt Lemon Mousse',
           glassware: 'Flute',
           servingtemp: '40 - 50 °F',
           colortxt: 'Straw to Light Amber',
           clarity:'Cloudy/ Hazy' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable' ,
           hop:'None' ,
           malt:'Grainy' ,
           esters:'N/A' ,
           phenols:'N/A' ,
           body:'Varies' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'N/A' ,
           hopsingr:'N/A' ,
           maltingr:'Pilsner and Wheat' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 41,
           name: 'English-Style Brown Ale',
           description: 'English-style brown ales range from dryer (Northern English) to sweeter (Southern English) maltiness. Roast malt tones (chocolate, nutty) may sometimes contribute to the flavor and aroma profile. Hop bitterness is very low to low, with very little hop flavor and aroma. Known for rich and advanced malt aroma and flavor without centering too much on hops, this style is extremely sessionable and food-friendly.',
           colornum: '12 - 25 SRM',
           bitterness: '15 - 25 IBU',
           alcoholnum: '4.5% - 5.5% ABV',
           foodpairings: 'Roasted Pork and Steak and Nuts, Aged Gouda, Pear Fritters',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Copper to Very Dark',
           clarity:'Clear' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma and flavor is very low. Hop bitterness is very low to low' ,
           malt:'Balance ranges from dry to sweet maltiness. Roast malt tones of toffee, nuts and caramel sometimes contribute to the flavor profile' ,
           esters:'Fruit(varies)' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Kent Goldings' ,
           maltingr:'Pale Ale, Special Roast, Victory, Crystal, Pale Chocolate' ,
           water:'Moderate carbonate water' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 42,
           name: 'English-Style Brown Porter',
           description: 'Brown porters have no roasted barley or strong burnt/black malt character. Low to medium malt sweetness, caramel and chocolate is acceptable. Hop bitterness is medium. Softer, sweeter and more caramel-like than a robust porter, with less alcohol and body. Porters are the precursor style to stouts.',
           colornum: '20 - 35 SRM',
           bitterness: '20 - 30 IBU',
           alcoholnum: '4.5% - 6.0% ABV',
           foodpairings: 'Roasted or Grilled Meats, Gruyere, Chocolate Peanut Butter Cookies',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Dark Brown (may have red tint) to Very Dark',
           clarity:'Opaque' ,
           carbonationvisual:'Slow to Fast Rising Bubbles' ,
           alcoholtxt:'Mild' ,
           hop:'Hop aroma and flavor are not perceived to medium. Hop bitterness is medium' ,
           malt:'Nutty, Chocolate, Caramel, Bready, Toffee' ,
           esters:'Fruity esters may be present' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium-high' ,
           hopsingr:'Fuggles' ,
           maltingr:'British Pale Ale, Brown, Crystal, Chocolate' ,
           water:'Moderate carbonate water' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 43,
           name: 'English-Style Mild',
           description: 'Malt and caramel are part of the flavor and aroma profile, while licorice and roast malt tones may sometimes contribute as well. Hop bitterness is very low to low. U.S. brewers are known to make lighter-colored versions as well as the more common ‘dark mild.’ These beers are very low in alcohol, yet often are still medium-bodied due to increased dextrin malts.',
           colornum: '17 - 34 SRM',
           bitterness: '10 - 24 IBU',
           alcoholnum: '3.2% - 4.0% ABV',
           foodpairings: 'Mushrooms and Wild Game, Mild Cheddar, Dark Fruit Tart',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Reddish Brown to Very Dark',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Not Detectable' ,
           hop:'Hop flavor is low to very low' ,
           malt:'Caramel, Chocolate, Coffee, Licorice, Raisin, Molasses. Malt flavors dominate the flavor profile' ,
           esters:'Fruity-ester flavors, if present, are very low to medium-low' ,
           phenols:'Not Common' ,
           body:'Soft to Mouth-Coating' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium-high' ,
           hopsingr:'Kent Goldings' ,
           maltingr:'British Pale Ale, Crystal, Pale Chocolate, Black Patent' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 44,
           name: 'English-Style India Pale Ale / IPA',
           description: 'Steeped in lore (and extra hops), the IPA is a stronger version of a pale ale. Characterized by stiff English-style hop character (earthy, floral) and increased alcohol content. English yeast lends a fruity flavor and aroma. Different from its American counterparts, this style strikes a balance between malt and hops for a more rounded flavor. There is also a lot of mythology surrounding the creation of this style, which is still debated today.',
           colornum: '6 - 14 SRM',
           bitterness: '35 - 63 IBU',
           alcoholnum: '5.0% - 7.0% ABV',
           foodpairings: 'Fettuccine Alfredo, Aged Cheddar, Ginger Spice Cake',
           glassware: 'Nonic Pint',
           servingtemp: '45 - 50 °F',
           colortxt: 'Gold to Copper',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Noticeable' ,
           hop:'Hop aroma is medium to high, often flowery. Hop flavor and bitterness are medium to high. Earthy and herbal English-variety hop character is perceived, but may be a result of the skillful use of hops of other national origins' ,
           malt:'Bready, Biscuit, Toast, Caramel, Toffee' ,
           esters:'Fruity ester aromas are moderate to very strong' ,
           phenols:'Not Common' ,
           body:'Moderate' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'British Pale Ale, Crystal, Biscuit' ,
           water:'High mineral content. May include subtle sulfur content' ,
           yeast:'Ale' 
            }),
                             knex('beertypes').insert(
       {
           id: 45,
           name: 'English-Style Oatmeal Stout',
           description: 'The addition of oatmeal adds a smooth, rich body to these beers. Oatmeal stouts are dark brown to black in color. Roasted malt character is caramel-like and chocolate-like, and should be smooth and not bitter. Coffee-like roasted barley and malt aromas are prominent. This low- to medium-alcohol style is packed with darker malt flavors and a rich and oily body from oatmeal.',
           colornum: '20 - 50 SRM',
           bitterness: '20 - 40 IBU',
           alcoholnum: '3.8% - 6.0% ABV',
           foodpairings: 'Chicken in Mole Sauce, Aged Cheddar, Sweet Potato Cheesecake',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 46,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 47,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 48,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 49,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 50,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 51,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 52,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 53,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 54,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 55,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 56,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 57,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 58,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 59,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 60,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 61,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 62,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 63,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 64,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 65,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 66,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 67,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 68,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 69,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 70,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 71,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 72,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 73,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 74,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 75,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 76,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 77,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 78,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 79,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 80,
           name: '',
           description: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            })

   );
};