
exports.seed = function(knex, Promise) {
 return Promise.join(
   // Deletes ALL existing entries
   knex('beertypes').del(),

   // Inserts seed entries
   knex('beertypes').insert(
       {
           id: 1,
           name: 'American Amber Ale',
           colornum: '11 - 18 SRM',
           bitterness: '30 - 45 IBU',
           alcoholnum: '4.4% - 6.1% ABV',
           foodpairings: 'Barbecue, Medium Cheddar, Banana Pound Cake',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Copper to Reddish Brown',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Citrus-like character is acceptable' ,
           malt:'Caramel' ,
           esters:'There may be below levels of fuity-ester flavor' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium' ,
           hopsingr:'Horizon, Cascade, Centennial' ,
           maltingr:'English Pale Ale or American Two-Row, Crystal, Victory' ,
           water:'Varies' ,
           yeast:'Ale' 
               }),
   knex('beertypes').insert(
       {
           id: 2,
           name: 'American Amber Lager',
           colornum: '6 - 14 SRM',
           bitterness: '18 - 30 IBU',
           alcoholnum: '4.8% - 5.8% ABV',
           foodpairings: 'Grilled Meats and Vegetables, White Cheddar, Fruit Desserts',
           glassware: 'Tulip',
           servingtemp: '45 - 50 °F',
           colortxt: 'Gold to Copper',
           clarity:'Clear to Slight Haze' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop flavor and aroma are very low to medium-high. Hop bitterness is very-low to medium-high' ,
           malt:'Low to medium-low caramel-type or toasted malt aromas are often present' ,
           esters:'Not Common' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Short to Medium' ,
           attenuation:'Medium' ,
           hopsingr:'German Noble' ,
           maltingr:'Two-Row, Munich, Vienna, Caramel' ,
           water:'Varies' ,
           yeast:'Lager' 
             }),
   knex('beertypes').insert(
       {
           id: 3,
           name: 'American Barley Wine',
           colornum: '11 - 22 SRM',
           bitterness: '60 - 100 IBU',
           alcoholnum: '8.4% - 12% ABV',
           foodpairings: 'Beef Cheek, Strong Blue Cheeses, Rich Desserts',
           glassware: 'Snifter',
           servingtemp: '50 - 55 °F',
           colortxt: 'Amber to Deep Red or Copper-Garnet',
           clarity:'Clear to Brilliant' ,
           carbonationvisual:'Slow to Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable to Hot' ,
           hop:'Hop aroma and flavor are medium to very high. Hop bitterness is high. American-type hops are often used, but not necessary for this style' ,
           malt:'Caramel, Toffee, Bready, Sweet' ,
           esters:'Fruit-ester flavors are often high' ,
           phenols:'Not common to style' ,
           body:'Mouth-Coating to Sticky' ,
           carbonationtaste:'Low to Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Magnum, Chinook, Centennial, Amarillo' ,
           maltingr:'Pale, Crystal, Pale Chocolate, Special "B"' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
     knex('beertypes').insert(
       {
           id: 4,
           name: 'American Black Ale',
           colornum: '34 - 38 SRM',
           bitterness: '50 - 70 IBU',
           alcoholnum: '6.0% - 7.5% ABV',
           foodpairings: 'Grilled Shrimp and Grits, Blue Cheeses and Aged Gouda, Chocolate Truffles',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Very Dark to Black',
           clarity:'Clear to Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma is medium-high to high, with hops of all origins contributing fruity, floral, herbal or other notes' ,
           malt:'Medium caramel malt and dark roasted malt aromas are evident' ,
           esters:'Can be Present' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
       knex('beertypes').insert(
       {
           id: 5,
           name: 'American Brett',
           colornum: 'Varies',
           bitterness: 'Varies',
           alcoholnum: 'Varies',
           foodpairings: 'Grilled or Roasted Game, Earthy Farmhouse Cheeses, Fruit-Filled Pastries',
           glassware: 'Tulip',
           servingtemp: '45 - 55 °F',
           colortxt: 'Varies',
           clarity:'Varies' ,
           carbonationvisual:'Varies' ,
           alcoholtxt:'Varies' ,
           hop:'Hop aroma, flavor and bitterness are evident over a full range from low to high' ,
           malt:'Varies' ,
           esters:'Can be Present' ,
           phenols:'Can be Present' ,
           body:'Varies' ,
           carbonationtaste:'Low to High' ,
           finishlength:'Varies' ,
           attenuation:'Varies' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Brettanomyces, Ale/Lager possible' 
            }),
         knex('beertypes').insert(
       {
           id: 6,
           name: 'American Brown Ale',
           colornum: '15 - 26 SRM',
           bitterness: '24 - 45 IBU',
           alcoholnum: '4.0% - 6.4% ABV',
           foodpairings: 'Grilled Meats and Vegetables, Aged Gouda, Pear Fritters',
           glassware: 'Nonic Pint',
           servingtemp: '50 - 55 °F',
           colortxt: 'Deep Copper to Very Dark Brown',
           clarity:'Clear' ,
           carbonationvisual:'Medium to Fast Rising Bubbles' ,
           alcoholtxt:'Mild to Noticeable' ,
           hop:'Hop aroma and flavor are low to medium. Hop bitternessis medium to high' ,
           malt:'Caramel, Chocolate, Toast' ,
           esters:'Fruity-ester flavors, if present, should be subdued' ,
           phenols:'Not Common' ,
           body:'Varies' ,
           carbonationtaste:'Medium to High' ,
           finishlength:'Medium' ,
           attenuation:'Medium' ,
           hopsingr:'U.S., U.K., Noble' ,
           maltingr:'Pale, Crystal, Chocolate, Victory' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
           knex('beertypes').insert(
       {
           id: 7,
           name: 'American Cream Ale',
           colornum: '2 - 5 SRM',
           bitterness: '10 - 22 IBU',
           alcoholnum: '4.3% - 5.7% ABV',
           foodpairings: 'Salads and Mild Shellfish, Monterey Jack, Lemon Custard Tart',
           glassware: 'Flute',
           servingtemp: '40 - 45 °F',
           colortxt: 'Straw to Gold',
           clarity:'Brilliant' ,
           carbonationvisual:'Fast Rising Bubbles' ,
           alcoholtxt:'Not Detectable to Mild' ,
           hop:'Hop aroma is usually absent, and hop flavor is very low to low. Hop bitterness is very low to low' ,
           malt:'Grainy' ,
           esters:'Not Common' ,
           phenols:'Not Common' ,
           body:'Soft' ,
           carbonationtaste:'High' ,
           finishlength:'Short' ,
           attenuation:'High' ,
           hopsingr:'Liberty' ,
           maltingr:'Pilsner' ,
           water:'Varies' ,
           yeast:'Lager or Ale' 
            }),
             knex('beertypes').insert(
       {
           id: 8,
           name: 'American Imperial Porter',
           colornum: '39 - 40 SRM',
           bitterness: '35 - 50 IBU',
           alcoholnum: '7.0% - 12.0% ABV',
           foodpairings: 'Chicken Mole Enchiladas, Smoked Gouda, Blondie Butterscotch Brownies',
           glassware: 'Tulip',
           servingtemp: '50 - 55 °F',
           colortxt: 'Black',
           clarity:'Opaque' ,
           carbonationvisual:'Medium Rising Bubbles' ,
           alcoholtxt:'Noticeable' ,
           hop:'Hop aroma and flavor are low to medium-high. Hop bitterness is medium-low to medium' ,
           malt:'No roasted barley or strong burnt/black malt character should be perceived. Medium malt, caramal and coacoa-like sweetness is present' ,
           esters:'Ale-like fruity ester flavors should be evident but not overpowering, complementing hop character and malt-derived sweetness' ,
           phenols:'Not Common' ,
           body:'Mouth-Coating' ,
           carbonationtaste:'Medium' ,
           finishlength:'Medium to Long' ,
           attenuation:'Medium' ,
           hopsingr:'Varies' ,
           maltingr:'Varies' ,
           water:'Varies' ,
           yeast:'Ale' 
            }),
               knex('beertypes').insert(
       {
           id: 9,
           name: 'American Imperial Red Ale',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                 knex('beertypes').insert(
       {
           id: 3,
           name: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                   knex('beertypes').insert(
       {
           id: 3,
           name: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                     knex('beertypes').insert(
       {
           id: 3,
           name: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                       knex('beertypes').insert(
       {
           id: 3,
           name: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                         knex('beertypes').insert(
       {
           id: 3,
           name: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                           knex('beertypes').insert(
       {
           id: 3,
           name: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            }),
                             knex('beertypes').insert(
       {
           id: 3,
           name: '',
           colornum: '',
           bitterness: '',
           alcoholnum: '',
           foodpairings: '',
           glassware: '',
           servingtemp: '',
           colortxt: '',
           clarity:'' ,
           carbonationvisual:'' ,
           alcoholtxt:'' ,
           hop:'' ,
           malt:'' ,
           esters:'' ,
           phenols:'' ,
           body:'' ,
           carbonationtaste:'' ,
           finishlength:'' ,
           attenuation:'' ,
           hopsingr:'' ,
           maltingr:'' ,
           water:'' ,
           yeast:'' 
            })

   );
};